import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NextSSRPlugin
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          {children}
          <Link 
            href="/like" 
            className="px-4 py-2 bg-white/10 backdrop-blur-md text-gray-800 font-semibold rounded-md 
              border border-white/20 shadow-sm
              hover:shadow-lg hover:shadow-white/20 hover:bg-white/20 
              transition-all duration-300 ease-out"
          >
            Liked Photos
          </Link>
        </AuthProvider>
      </body>
    </html>
  );
}
